# Generated by Django 5.2.15 on 2026-07-15 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrm_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaverequest',
            name='half_day',
            field=models.BooleanField(default=False),
        ),
    ]
