# Generated by Django 6.0.7 on 2026-07-26 09:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrm_app', '0004_attendance_source_added_by'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=150)),
                ('company_email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=30)),
                ('address', models.TextField()),
                ('timezone', models.CharField(default='Asia/Dhaka', max_length=50)),
                ('currency', models.CharField(default='BDT', max_length=10)),
                ('date_format', models.CharField(default='DD-MM-YYYY', max_length=20)),
                ('company_logo', models.ImageField(blank=True, null=True, upload_to='company_logo/')),
                ('maintenance_mode', models.BooleanField(default=False)),
            ],
        ),
        migrations.AlterModelOptions(
            name='payrolladjustment',
            options={'ordering': ['-created_at']},
        ),
        migrations.CreateModel(
            name='UserPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('module', models.CharField(choices=[('employees', 'Employees'), ('attendance', 'Attendance'), ('leave', 'Leave Management'), ('tasks', 'Task Management'), ('documents', 'Documents'), ('salary', 'Salary'), ('payroll', 'Payroll'), ('assets', 'Assets'), ('settings', 'Settings')], max_length=50)),
                ('can_view', models.BooleanField(default=False)),
                ('can_create', models.BooleanField(default=False)),
                ('can_edit', models.BooleanField(default=False)),
                ('can_delete', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custom_permissions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'module')},
            },
        ),
    ]
