# Generated by Django 6.0.7 on 2026-08-01 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrm_app', '0005_sitesettings_alter_payrolladjustment_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userpermission',
            options={'ordering': ['module']},
        ),
        migrations.AddField(
            model_name='lateentry',
            name='title',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='leaverequest',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='leave_attachments/'),
        ),
        migrations.AddField(
            model_name='leaverequest',
            name='title',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='userpermission',
            name='module',
            field=models.CharField(choices=[('dashboard', 'Dashboard'), ('notice', 'Notice & Announcements'), ('users', 'Users & Employees'), ('onboarding', 'Onboarding & NDA'), ('profile', 'My Profile'), ('attendance', 'Attendance'), ('late', 'Late Management'), ('leave', 'Leave Management'), ('tasks', 'Task Management'), ('documents', 'Document Management'), ('salary', 'Payroll & Salary'), ('payroll', 'Payroll'), ('petty_cash', 'Petty Cash'), ('assets', 'Asset Management'), ('files', 'Files & Credentials'), ('configuration', 'Configuration'), ('upload_center', 'Upload Center'), ('support', 'Support & Help'), ('calendar', 'Calendar')], max_length=50),
        ),
    ]
