# Generated by Django 6.0.7 on 2026-08-02 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrm_app', '0006_alter_userpermission_options_lateentry_title_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoleMenuPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('super_admin', 'Super Admin'), ('manager', 'Manager'), ('employee', 'Employee')], max_length=20)),
                ('menu', models.CharField(choices=[('dashboard', 'Dashboard'), ('notice', 'Notice & Announcements'), ('users', 'Users & Employees'), ('onboarding', 'Onboarding & NDA'), ('profile', 'My Profile'), ('attendance', 'Attendance'), ('late', 'Late Management'), ('leave', 'Leave Management'), ('tasks', 'Task Management'), ('documents', 'Document Management'), ('salary', 'Payroll & Salary'), ('payroll', 'Payroll'), ('petty_cash', 'Petty Cash'), ('assets', 'Asset Management'), ('files', 'Files & Credentials'), ('configuration', 'Configuration'), ('upload_center', 'Upload Center'), ('support', 'Support & Help'), ('calendar', 'Calendar')], max_length=50)),
                ('is_allowed', models.BooleanField(default=False)),
            ],
            options={
                'unique_together': {('role', 'menu')},
            },
        ),
    ]
