# Generated by Django 5.2.15 on 2026-08-08 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrm_app', '0008_alter_task_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='color',
            field=models.CharField(default='#FF6B00', help_text='Task card color in hex format', max_length=7),
        ),
    ]
