# Generated by Django 5.2.15 on 2026-08-08 18:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrm_app', '0010_remove_bankaccount_status_bankaccount_color'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('Experience Letter', 'Experience Letter'), ('Salary Certificate', 'Salary Certificate'), ('NOC', 'NOC (No Objection Certificate)'), ('Joining Letter', 'Joining Letter'), ('Promotion Letter', 'Promotion Letter'), ('Relieving Letter', 'Relieving Letter'), ('Other', 'Other')], max_length=50)),
                ('custom_type', models.CharField(blank=True, help_text='Specify if "Other" is selected', max_length=200)),
                ('reason', models.TextField(help_text='Reason for document request')),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected'), ('Completed', 'Completed')], default='Pending', max_length=20)),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, help_text='Admin notes for approval/rejection')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requested_documents', to='hrm_app.employee')),
                ('generated_document', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='request_source', to='hrm_app.document')),
                ('requester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='document_requests', to=settings.AUTH_USER_MODEL)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-requested_at'],
            },
        ),
    ]
