# Generated by Django 5.2.15 on 2026-08-09 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrm_app', '0011_documentrequest'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bankaccount',
            name='color',
        ),
        migrations.AddField(
            model_name='bankaccount',
            name='status',
            field=models.CharField(default='Active', max_length=20),
        ),
        migrations.AlterField(
            model_name='task',
            name='color',
            field=models.CharField(default='#FF6B00', max_length=7),
        ),
        migrations.DeleteModel(
            name='DocumentRequest',
        ),
    ]
