# Generated by Django 6.0.7 on 2026-08-09 10:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrm_app', '0013_documentrequest'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bankaccount',
            name='status',
        ),
        migrations.AddField(
            model_name='bankaccount',
            name='color',
            field=models.CharField(default='#FF6B00', help_text='Task card color in hex format', max_length=7),
        ),
        migrations.AlterField(
            model_name='documentrequest',
            name='custom_type',
            field=models.CharField(blank=True, help_text='Specify if "Other" is selected', max_length=200),
        ),
        migrations.AlterField(
            model_name='documentrequest',
            name='document_type',
            field=models.CharField(choices=[('Experience Letter', 'Experience Letter'), ('Salary Certificate', 'Salary Certificate'), ('NOC', 'NOC (No Objection Certificate)'), ('Joining Letter', 'Joining Letter'), ('Promotion Letter', 'Promotion Letter'), ('Relieving Letter', 'Relieving Letter'), ('Other', 'Other')], max_length=50),
        ),
        migrations.AlterField(
            model_name='documentrequest',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requested_documents', to='hrm_app.employee'),
        ),
        migrations.AlterField(
            model_name='documentrequest',
            name='notes',
            field=models.TextField(blank=True, help_text='Admin notes for approval/rejection'),
        ),
        migrations.AlterField(
            model_name='documentrequest',
            name='reason',
            field=models.TextField(help_text='Reason for document request'),
        ),
        migrations.AlterField(
            model_name='documentrequest',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='task',
            name='color',
            field=models.CharField(default='#FF6B00', help_text='Task card color in hex format', max_length=7),
        ),
    ]
