# Generated by Django 6.0.7 on 2026-08-12 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrm_app', '0014_remove_bankaccount_status_bankaccount_color_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='blocked_color',
            field=models.CharField(default='#EF4444', help_text='Color for Blocked column', max_length=7),
        ),
        migrations.AddField(
            model_name='project',
            name='completed_color',
            field=models.CharField(default='#10B981', help_text='Color for Completed column', max_length=7),
        ),
        migrations.AddField(
            model_name='project',
            name='in_progress_color',
            field=models.CharField(default='#F59E0B', help_text='Color for In Progress column', max_length=7),
        ),
        migrations.AddField(
            model_name='project',
            name='todo_color',
            field=models.CharField(default='#6B7280', help_text='Color for To Do column', max_length=7),
        ),
    ]
