# Generated by Django 5.2.15 on 2026-08-12 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrm_app', '0015_project_blocked_color_project_completed_color_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='document_type',
            field=models.CharField(choices=[('request', 'Request Document'), ('generated', 'Generated Document'), ('employee', 'Employee Document'), ('office', 'Office Document')], default='office', help_text='Type of document for filtering', max_length=20),
        ),
    ]
