# Generated by Django 5.2.15 on 2026-08-12 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrm_app', '0016_document_document_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='is_approved',
            field=models.BooleanField(default=False, help_text='Admin approval for employee documents'),
        ),
    ]
