# Generated by Django 6.0.7 on 2026-08-12 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrm_app', '0017_document_is_approved'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rolemenupermission',
            old_name='is_allowed',
            new_name='can_create',
        ),
        migrations.AddField(
            model_name='rolemenupermission',
            name='can_delete',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='rolemenupermission',
            name='can_edit',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='rolemenupermission',
            name='can_view',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='userpermission',
            name='can_create',
            field=models.BooleanField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='userpermission',
            name='can_delete',
            field=models.BooleanField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='userpermission',
            name='can_edit',
            field=models.BooleanField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='userpermission',
            name='can_view',
            field=models.BooleanField(blank=True, default=None, null=True),
        ),
    ]
