# Generated by Django 6.0.7 on 2026-08-23 07:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrm_app', '0018_rename_is_allowed_rolemenupermission_can_create_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='blocked_color',
        ),
        migrations.RemoveField(
            model_name='project',
            name='completed_color',
        ),
        migrations.RemoveField(
            model_name='project',
            name='in_progress_color',
        ),
        migrations.RemoveField(
            model_name='project',
            name='todo_color',
        ),
        migrations.CreateModel(
            name='TaskStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('color', models.CharField(default='#6B7280', help_text='Kanban column color in hex format', max_length=7)),
                ('order', models.PositiveIntegerField(default=0, help_text='Order of the status on the Kanban board')),
                ('active', models.BooleanField(default=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_statuses', to='hrm_app.project')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tasks', to='hrm_app.taskstatus'),
        ),
        migrations.AddConstraint(
            model_name='taskstatus',
            constraint=models.UniqueConstraint(fields=('project', 'name'), name='unique_task_status_per_project'),
        ),
    ]
