# Generated by Django 6.0.7 on 2026-08-23 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrm_app', '0019_remove_project_blocked_color_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rolemenupermission',
            name='menu',
            field=models.CharField(choices=[('dashboard', 'Dashboard'), ('notice', 'Notice & Announcements'), ('users', 'Users & Employees'), ('onboarding', 'Onboarding & NDA'), ('profile', 'My Profile'), ('attendance', 'Attendance'), ('late', 'Late Management'), ('leave', 'Leave Management'), ('tasks', 'Task Management'), ('documents', 'Document Management (All)'), ('documents_request', 'Document - Request'), ('documents_generate', 'Document - Generate'), ('documents_employee', 'Document - Employee'), ('documents_office', 'Document - Office'), ('salary', 'Payroll & Salary'), ('payroll', 'Payroll'), ('petty_cash', 'Petty Cash'), ('assets', 'Asset Management'), ('files', 'Files & Credentials'), ('configuration', 'Configuration'), ('upload_center', 'Upload Center'), ('support', 'Support & Help'), ('calendar', 'Calendar')], max_length=50),
        ),
        migrations.AlterField(
            model_name='userpermission',
            name='module',
            field=models.CharField(choices=[('dashboard', 'Dashboard'), ('notice', 'Notice & Announcements'), ('users', 'Users & Employees'), ('onboarding', 'Onboarding & NDA'), ('profile', 'My Profile'), ('attendance', 'Attendance'), ('late', 'Late Management'), ('leave', 'Leave Management'), ('tasks', 'Task Management'), ('documents', 'Document Management (All)'), ('documents_request', 'Document - Request'), ('documents_generate', 'Document - Generate'), ('documents_employee', 'Document - Employee'), ('documents_office', 'Document - Office'), ('salary', 'Payroll & Salary'), ('payroll', 'Payroll'), ('petty_cash', 'Petty Cash'), ('assets', 'Asset Management'), ('files', 'Files & Credentials'), ('configuration', 'Configuration'), ('upload_center', 'Upload Center'), ('support', 'Support & Help'), ('calendar', 'Calendar')], max_length=50),
        ),
    ]
