# Generated by Django 6.0.7 on 2026-08-30 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrm_app', '0020_alter_rolemenupermission_menu_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='color',
            field=models.CharField(default='#FF6B00', help_text='Task card color', max_length=7),
        ),
    ]
