# Generated by Django 5.2.15 on 2026-08-31 14:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrm_app', '0022_fix_task_status_column'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Step description', max_length=200)),
                ('completed', models.BooleanField(default=False, help_text='Whether this step is completed')),
                ('order', models.PositiveIntegerField(default=0, help_text='Order of the step')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='hrm_app.task')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
    ]
