# Generated by Django 6.0.7 on 2026-09-01 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrm_app', '0023_taskstep'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='document',
            field=models.FileField(blank=True, help_text='Optional document for this task', null=True, upload_to='task_documents/'),
        ),
        migrations.AddField(
            model_name='task',
            name='image',
            field=models.ImageField(blank=True, help_text='Optional image for this task', null=True, upload_to='task_images/'),
        ),
        migrations.AlterField(
            model_name='asset',
            name='status',
            field=models.CharField(choices=[('Available', 'Available'), ('In Use', 'In Use'), ('Overdue', 'Overdue'), ('Maintenance', 'Maintenance'), ('Retired', 'Retired')], default='Available', max_length=15),
        ),
    ]
