# Generated by Django 6.0.7 on 2026-09-03 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrm_app', '0024_task_document_task_image_alter_asset_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payrolladjustment',
            name='adjustment_type',
            field=models.CharField(choices=[('Bonus', 'Bonus'), ('Incentive', 'Incentive'), ('Advance', 'Advance'), ('Deduction', 'Deduction'), ('Increase', 'Salary Increase'), ('Decrease', 'Salary Decrease')], max_length=20),
        ),
    ]
