# Generated by Django 6.0.7 on 2026-09-12 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrm_app', '0028_expensecategory_fixedcost'),
    ]

    operations = [
        migrations.AddField(
            model_name='securefile',
            name='access_group',
            field=models.CharField(default='Engineering', max_length=50),
        ),
        migrations.AddField(
            model_name='securefile',
            name='type',
            field=models.CharField(choices=[('Cloud', 'Cloud'), ('SSH / Root', 'SSH / Root'), ('Email', 'Email'), ('Web', 'Web'), ('Other', 'Other')], default='Cloud', max_length=30),
        ),
        migrations.AlterField(
            model_name='securefile',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='secure/'),
        ),
    ]
