# Generated by Django 6.0.7 on 2026-09-13 10:03

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrm_app', '0030_alter_sitesettings_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bankaccount',
            options={'ordering': ['bank_name']},
        ),
        migrations.RemoveField(
            model_name='bankaccount',
            name='branch',
        ),
        migrations.RemoveField(
            model_name='bankaccount',
            name='color',
        ),
        migrations.RemoveField(
            model_name='bankaccount',
            name='employee',
        ),
        migrations.RemoveField(
            model_name='bankaccount',
            name='is_primary',
        ),
        migrations.AddField(
            model_name='bankaccount',
            name='branch_name',
            field=models.CharField(default='', max_length=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bankaccount',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bankaccount',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='bankaccount',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='bankaccount',
            name='account_number',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='bankaccount',
            name='bank_name',
            field=models.CharField(max_length=150),
        ),
    ]
