# Generated by Django 6.0.7 on 2026-09-15 16:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrm_app', '0031_support_models'),
    ]

    operations = [
        migrations.AddField(
            model_name='supportconversation',
            name='participant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='support_participating_conversations', to=settings.AUTH_USER_MODEL),
        ),
    ]
