# Generated by Django 6.0.7 on 2026-09-15 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrm_app', '0032_supportconversation_participant'),
    ]

    operations = [
        migrations.AddField(
            model_name='supportmessage',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='support/chat/'),
        ),
        migrations.AddField(
            model_name='supportticket',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='support/tickets/'),
        ),
    ]
