# Generated by Django 6.0.7 on 2026-09-17 09:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrm_app', '0033_supportmessage_attachment_supportticket_attachment'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeaveReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('from_date', models.DateField()),
                ('to_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='hrm_app.employee')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
