# Generated by Django 6.0.7 on 2026-09-17 09:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hrm_app', '0034_leavereport'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leavereport',
            name='name',
        ),
    ]
